require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/DocumentationMethod:
  Enabled: true

Naming/MethodName:
  Exclude:
    - lib/f_service/base.rb

RSpec/ContextWording:
  Prefixes:
    - and
    - but
    - when
    - with
    - without

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Enabled: false
